# -*- coding: utf-8 -*-
"""L6 E6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Pgqz3AlN4yrNa78k6qRkpDfMtoQ8gG7
"""

#Escreva um programa que crie uma pasta chamada "Arquivos Teste". 
#O programa então deve criar 100 arquivos de texto dentro da pasta 
#"Arquivos Teste". Os arquivos de texto devem ser nomeados com 
#números sequenciais de um ao cem, sempre com três dígitos. 
#O primeiro arquivo deve chamar "001.txt"  o último "100.txt".

#Bilbiotecas
import os

#Criamos a pasta alvo
pasta_alvo = "Arquivos Teste/"
if(not os.path.exists(pasta_alvo)):
  os.mkdir(pasta_alvo)

#Criamos os arquivos de texto
for i in range(100):
  a = open(pasta_alvo + ("%03d.txt" % (i+1)), "w")
  a.close()