# -*- coding: utf-8 -*-
"""L6 E3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CC74IvFSbMhPSOPDCqXXXZ4o3s_dfQzH
"""

#Escreva um programa que exiba o caminho absoluto de todas as 
#imagens de formato ".png" na pasta "Meus Arquivos". 
#A pasta "Meus Arquivos" deve estar presente no mesmo local em que 
#a resolução desse exercício estiver. 
#Somente  o caminho das imagens deve ser exibidos.

import glob, os

caminho = "Meus Arquivos/"

#Utilizando glob
imagens = glob.glob(caminho + "*.png")
print(imagens)

#Utilizando os
arquivos_e_pastas = os.listdir(caminho)
for elemento in arquivos_e_pastas:
  if(os.path.isfile(caminho + elemento)):
    if(elemento[-4:] == ".png"):
      print(caminho + elemento)