# -*- coding: utf-8 -*-
"""L6 E1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wVSIzCpb6ncMM60qTLD48j2b0UzMDsRp
"""

#Escreva um programa que exiba o nome de todos os arquivos 
#presentes na pasta "Meus Arquivos". A pasta "Meus Arquivos" 
#deve estar presente no mesmo local em que a resolução desse 
#exercício estiver. Somente os arquivos devem ser exibidos, 
#ignorando diretórios.

import os


#Main
caminho = "Meus Arquivos/"

pastas_e_arquivos = os.listdir(caminho)

for elemento in pastas_e_arquivos:
  if(os.path.isfile(caminho + elemento)):
    print(elemento)