# -*- coding: utf-8 -*-
"""L6 E2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dyK3AidNOftWIEfAOa5b5WnzTCwZl1IP
"""

#Escreva um programa que verifique se o arquivo 
#"Meus Arquivos/Dia de sol na praia.png" existe. 
#O programa então deverá exibir na tela se o arquivo existe ou não. 
#Caso o arquivo exista, o programa então deve exibir o tamanho do arquivo.

#Biblioteca
import os

caminho = "Meus Arquivos/Dia de sol na praia.png"

if(os.path.exists(caminho)):
  print("O arquivo existe. O tamanho do arquivo é %.2fMb" % (os.path.getsize(caminho)/(1024*1024)))
else:
  print("O arquivo não existe")