# -*- coding: utf-8 -*-
"""L6 E5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SHoEa_i8T0yeiZ5xYk6raIQ3I3EkTq-X
"""

#Escreva um programa que leia cem números presente em um arquivo nomeado 
#"números.txt". O arquivo possui cem números, um número por linha. 
#O seu programa deve ler todos os números do arquivo e os guardar em uma lista. 
#Ao fim do programa a lista com todos os números deve ser exibida na tela.

#Main

#Abrir o arquivo
a = open("números.txt", "r")

#Ler os números
numeros = []
for i in range(100):
  num = a.readline()
  num = num[:-1]
  num = int(num)
  numeros.append(num)

#Imprimir a Lista
print(numeros)