# -*- coding: utf-8 -*-
"""L6 E4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EIxUasyn4TZMzmhobxKh8wiHnymw4ZF1
"""

#Escreva um programa que crie um arquivo de texto nomeado "números.txt". 
#O programa então deve escrever no arquivo a sequência de números de 
#um ao cem, um número por linha do arquivo.

#Main

#Criar o arquivo
a = open("números.txt", "w")

#Inserir os números
for i in range(100):
  num = "%d\n" % (i+1)
  a.write(num)

#Fechar o arquivo
a.close()