# -*- coding: utf-8 -*-
"""Exercício 06 - Multiplicar Elementos de uma Lista.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10pFFqJvQdXyOUhWcG5OyjBQVOFDJPH01
"""

#Escreva um programa utilizando a linguagem python com uma 
#função que receba uma lista de números inteiros e retorne 
#todos os elementos da lista multiplicados entre si.
#Para a seguinte entrada:
  #[1, 5, 2, 6, 3]
#A função deverá retornar:
  #180

#Funções
def multiplicar_lista(lista):
  resultado = lista[0]
  for i in range(1, len(lista)):
    resultado = resultado * lista[i]
  #print(resultado)

  #resultado = 1
  #for i in lista:
    #resultado = resultado * i
  #print(resultado)

  return resultado

#Main
lista = [1, 5, 2, 6, 3]
print(multiplicar_lista(lista))