# -*- coding: utf-8 -*-
"""Exercício 05 - Calcular Fatorial de um Número.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XfRl2GnuA6_3mAOE5pSU-M37BX2iz_oC
"""

#Escreva um programa utilizando a linguagem python com uma função 
#que calcule o fatorial de um número inteiro.
#Para a seguinte entrada:
  #5
#A função deverá retornar:
  #120

#Função
def fatorial(num):
  fatorial = 1

  for i in range(2, num+1):
    fatorial = fatorial * i

  return fatorial

#Main
print(fatorial(6))