# -*- coding: utf-8 -*-
"""Exercício 02 - Contar Letras Minúsculas e Maiúsculas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ux5milwAX4YGEa2hOxdFeEa4aCJGM5n0
"""

#Escreva um programa utilizando a linguagem python com uma função que receba 
#uma frase (string). A função então deverá retornar a quantidade de letras
#maiúsculas e minúsculas na frase. 
#A função deverá retornar ambos os valores em uma única execução.

#Para a seguinte entrada: 
  #Frase de Teste

#A função deverá retornar: 
  #Quantidade de letras maiúsculas: 2
  #Quantidade de letras minúsculas: 10

# Funções
def contar_letras(string):
  qtt_minus = 0
  qtt_maisc = 0

  for i in range(len(string)):
    if(string[i].islower()):
      qtt_minus += 1
    elif(string[i].isupper()):
      qtt_maisc += 1

  return qtt_minus, qtt_maisc

# Main
string_teste = "Frase de Teste"
qtt_minus, qtt_maisc = contar_letras(string_teste)
print("Quantidade de letras minúsculas: %d" % qtt_minus)
print("Quantidade de letras maiúsculas: %d" % qtt_maisc)