# -*- coding: utf-8 -*-
"""Exercício 04 - Verificar se Palavras são Anagramas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ONkcWBe8afOEZg-W3tiQRkuqmsamzpCg
"""

#Escreva um programa utilizando a linguagem python com uma função 
#que receba duas cadeias de caracteres (strings). 
#A função então deverá verificar se as strings são anagramas uma da outra. 
#Um anagrama é uma palavra ou frase criada a partir da transposição 
#de letras de outra. A função deverá retornar True caso as palavras 
#sejam anagramas ou False caso contrário.

#Para a seguinte entrada: 
  #amor roma

#A função deverá retornar: 
  #True

#Funções
def verificar_anagrama(string1, string2):
  flag = False

  string1_ordenada = sorted(string1)
  string2_ordenada = sorted(string2)

  print(string1_ordenada, string2_ordenada)

  if(string1_ordenada == string2_ordenada):
    flag = True

  return flag

#Main
print(verificar_anagrama("amor", "roma"))