# -*- coding: utf-8 -*-
"""Exercício 03 - Imprimir as Potências de um Número.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VC388chjb43EI0YReOMENFPT6NhPh5eH
"""

#Escreva um programa utilizando a linguagem python com uma função 
#que receba um número inteiro K. A função então deverá imprimir 
#K elevado as potencias de 0 até 10.

#Para a seguinte entrada: 
  #2

#A função deverá imprimir: 
  #1
  #2
  #4
  #8
  #16
  #32
  #64
  #128
  #256
  #512
  #1024

# Função
def imprimir_potencias(K, potencias=[0, 10]):
  for i in range(potencias[0], potencias[1]+1, 1):
    print(K**i)

# Main
imprimir_potencias(2)