# -*- coding: utf-8 -*-
"""Exercício 01 - Trocar o Valor de duas Variáveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qI1D0YzW-dwRHC42BrsvDx_EAylESizW
"""

#Escreva um programa utilizando a linguagem python com uma função 
#que receba um dicionário com dois elementos. 
#A função então deverá trocar o valor dos dois elementos. 
#A função receberá um dicionário com as chaves K e J 
#e deverá atribuir a J o valor inicial de K e a K o valor 
#inicial de J.

#Para a seguinte entrada: 
  #{"K":5, "J":7}

#Ao fim da execução os valores das variáveis deverão ser:
 #{"K":7, "J":5}

#Função
def trocar_valores(dicionario):
  temp = dicionario["K"]
  dicionario["K"] = dicionario["J"]
  dicionario["J"] = temp

#Main
dicionario_test = {"K":5,
                   "J":7}
print("O valor de K é %d e J é %d" % (dicionario_test["K"], \
                                       dicionario_test["J"]))
trocar_valores(dicionario_test)
print("O valor de K é %d e J é %d" % (dicionario_test["K"], \
                                       dicionario_test["J"]))