# -*- coding: utf-8 -*-
"""Exercício 07 - Verificar se um Número é Número Primo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1crxgy9H3bpFOv4Yk874jfg3D_kSy_iJ8
"""

#Escreva um programa utilizando a linguagem python com uma função 
#que verifique se um número inteiro é primo. Um número primo é 
#um número natural (maior que 1) cujos divisores inteiros são 
#somente 1 e o próprio número.
#Para a seguinte entrada:
  #7
#A função deverá retornar:
  #O número informado (7) é um número primo.
#Para a seguinte entrada:
  #8
#A função deverá retornar:
  #O número informado (8) não é um número primo.

#Funções
def verificar_primo(num):
  flag = True

  for i in range(2, int(num/2)+1):
    if((num % i) == 0):
      flag = False

  return flag

#Main
teste = 9
if(verificar_primo(teste)):
  print("O número informado (%d) é um número primo." % teste)
else:
  print("O número informado (%d) não é um número primo." % teste)