# -*- coding: utf-8 -*-
"""L4 E2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gUOwJ-mKhU2iV03JlQKVRw844FUBgJSw
"""

#Escreva um programa que calcule a quantidade de latas de tinta 
#e o custo para pintar um tanques cilíndrico de combustível. Serão 
#fornecidos o raio e a altura desse cilindro. 
#Assuma o custo de uma lata de tinta como sendo R$75,00.

#Sabe-se que:
#a) Cada lata de tinta contém 5 litros
#b) Cada litro de tinta pinta 3 metros quadrados;
#c) Área do cilindro = 2 vezes a área da base + circunferência da base 
#vezes a altura;
#d) O raio e altura do cilíndro serão os dados de entrada.

import math
#Funções
def area_cilindro(altura, raio):
  area = 2 * (math.pi * raio * raio)
  area += 2*math.pi*raio*altura
  return area

def calcular_latas_para_pintura(altura, raio):
  area_por_lata = 5 * 3
  area_para_pintar = area_cilindro(altura, raio)

  qtt_latas = math.ceil(area_para_pintar / area_por_lata)
  return qtt_latas

#Main
altura = float(input("Por favor insira a altura: "))
raio = float(input("Por favor insira o raio: "))
preco_lata = 75
qtt_latas = calcular_latas_para_pintura(altura, raio)

print("A quantidade de latas necessárias é %d" % qtt_latas)
print("O custo para pintar o cilíndro é R$%d" % (qtt_latas * preco_lata))