# -*- coding: utf-8 -*-
"""L4 E5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CwxQ6p8tkgHXjWsutkvQ1nhB1hM-Tt9K
"""

#Escreva um programa que, dada a função (3/5)x**5 + 5x**3 − 3x**2 + 9x, 
#calcule o valor de um ponto aplicado na função e em suas primeira 
#e segunda derivadas. 
#O seu programa deve oferecer o seguinte menu ao usuário:

#a) 1 - Verificar o valor da função em um ponto
#b) 2 - Verificar o valor da primeira derivada da função em um ponto
#c) 3 - Verificar o valor da segunda derivada da função em um ponto
#d) 9 - Sair do Programa

#Observação 1: Todos os valores informados e calculados no programa devem 
#ser pontos flutuantes.
#Observação 2: Todos os valores exibidos pelas operações do programa devem 
#ser apresentados com oito casas decimais de precisão.
#Observação 3: Depois de executada qualquer operação, com exceção de 
#"Sair do Programa", o menu deve ser exibido novamente para o usuário.
#Observação 4: Todas as operações, com exceção de "Sair do Programa", devem ser
#executadas por funções implementadas por você.

#Funções
def exibir_menu():
  print("\n1 - Verificar o valor da função em um ponto")
  print("2 - Verificar o valor da primeira derivada da função em um ponto")
  print("3 - Verificar o valor da segunda derivada da função em um ponto")
  print("9 - Sair do Programa\n")

def f(x):
  valor_f = (3/5)*(x**5) + 5*(x**3) - 3*(x**2) + 9*x
  return valor_f

def d1(x):
  valor_d1 = 3*(x**4) + 15*(x**2) - 6*x + 9
  return valor_d1

def d2(x):
  valor_d2 = 12*(x**3) +  30*x - 6 
  return valor_d2

#Main
exibir_menu()
opcao = int(input("Por favor informe a opção desejada: "))

while(opcao != 9):
  if(opcao == 1):
    x = float(input("Por favor informe o ponto desejado: "))
    print("%.8f" % f(x))
  elif(opcao == 2):
    x = float(input("Por favor informe o ponto desejado: "))
    print("%.8f" % d1(x))
  elif(opcao == 3):
    x = float(input("Por favor informe o ponto desejado: "))
    print("%.8f" % d2(x))

  exibir_menu()
  opcao = int(input("Por favor informe a opção desejada: "))