# -*- coding: utf-8 -*-
"""L4 E3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rMzHsft8U9dX-OxNxgvfj6Bm9UlAYrH2
"""

#Crie um programa que receba um vetor V de sete números inteiros e um 
#número inteiro N. O programa então deve exibir o menu a seguir com as 
#seguintes funcionalidades:
#a) 1 - Somar (V + N)
#b) 2 - Subtrair (V − N)
#c) 3 - Multiplicar (V ∗ N)
#d) 4 - Dividir ( V / N )
#e) 5 - Elevar (V^{N})
#f) 9 - Sair do Programa

#Onde:
#Somar: Soma o valor N a todos os elementos de V
#Subtrair : Subtrai N de todos os elementos de V
#Multiplicar: Multiplica todos os valores de V por N
#Dividir: Divide todos os valores de V por N
#Elevar: Eleva todos os valores de V à N
#Sair do Programa: Encerra o programa

#Observação 1: O vetor modificado deve ser exibido depois de cada operação 
#executada, com exceção de "Sair do Programa".
#Observação 2: Depois de executada qualquer operação, com exceção de 
#"Sair do Programa", o menu deve ser exibido novamente para o usuário.
#Observação 3: As operações devem ser executadas sobre o vetor original 
#informado pelo usuário.

#Bibliotecas
import numpy as np

#Função
def exibir_menu():
  print("\n1 - Somar (V + N)")
  print("2 - Subtrair (V − N)")
  print("3 - Multiplicar (V ∗ N)")
  print("4 - Dividir ( V / N )")
  print("5 - Elevar (V^{N})")
  print("9 - Sair do Programa\n")

#Main
#receber entradas
v = []
for i in range(7):
  temp = int(input("Insira o elemento V[%d]: " % i))
  v.append(temp)

v = np.asarray(v, dtype=int)

n = int(input("Por favor insira o valor de N: "))

exibir_menu()
opcao_usuario = int(input("Informe a operação desejada: "))

while(opcao_usuario != 9):
  if(opcao_usuario == 1):
    print(v + n)
  elif(opcao_usuario == 2):
    print(v - n)
  elif(opcao_usuario == 3):
    print(v * n)
  elif(opcao_usuario == 4):
    print(v / n)
  elif(opcao_usuario == 5):
    print(v ** n)

  exibir_menu()
  opcao_usuario = int(input("Informe a operação desejada: "))