# -*- coding: utf-8 -*-
"""L4 E1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zRv_WDAGAM-pPwpJRhaGPJ9XHa53MnMn
"""

#Escreva um programa que receba o início do código de rastreio de uma 
#encomenda. O programa então deverá imprimir de qual estado a encomenda 
#saiu de acordo com a lista abaixo. O programa deverá possuir uma função 
#chamada rastrear_encomenda, que receberá o código de rastreio 
#e imprimirá na tela a região de origem da encomenda.
#a) 1 - Maranhão
#b) 2 - Piauí
#c) 3 - Ceara
#d) 4 - Bahia
#e) 5 ou 6 - Sergipe
#f) 7, 8 ou 9 - Alagoas
#g) C.C. - Não Cadastrado

#Funções
def rastrear_encomenda(codigo):

  if(codigo == 1):
    print("Maranhão")
  elif(codigo == 2):
    print("Piauí")
  elif(codigo == 3):
    print("Ceara")
  elif(codigo == 4):
    print("Bahia")
  elif((codigo == 5) or (codigo == 6)):
    print("Sergipe")
  elif((codigo == 7) or (codigo == 8) or (codigo == 9)):
    print("Alagoas")
  else:
    print("Não Cadastrado")

#Main
codigo = int(input("Por favor insira o código de rastreio: "))
rastrear_encomenda(codigo)