# -*- coding: utf-8 -*-
"""Converter_Imagem_Para_Tons_de_Cinza.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LTOOnH0-gsVKS4z2IBQiWUCCQZUHi_5b
"""

#Abrir uma imagem chama "praia.png"
#Converter a imagem para tons de cinza
#Guardar a imagem em tons de cinza

import cv2

#Abrir a imagem
caminho_imagem = "praia.png"
imagem = cv2.imread(caminho_imagem)

#Converter para tons de Cinza
imagem_convertida = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)

#Guardar a Imagem
caminho_saida = caminho_imagem.replace(".png", "_cinza.png")
cv2.imwrite(caminho_saida, imagem_convertida)

import cv2

#Abrir a imagem
caminho_imagem = "praia.png"
imagem_convertida = cv2.imread(caminho_imagem, cv2.IMREAD_GRAYSCALE)

#Guardar a Imagem
caminho_saida = caminho_imagem.replace(".png", "_cinza2.png")
cv2.imwrite(caminho_saida, imagem_convertida)