# -*- coding: utf-8 -*-
"""L5 E7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16lTOXC3S0z-iwQTJ6GAjEqzHQEBjg_m7
"""

#Escreva um programa que dada uma string A, substitua todas as 
#ocorrências de "Banana" por "Maçã".

#Para a string: Fui à feira das bananas comprar umas bananas para o café.
#A string final deve ser: Fui à feira das maçãs comprar umas maçãs para o café.

#Main
frase_teste = "Fui à feira das bananas comprar umas bananas para o café."
frase_teste = frase_teste.replace("banana", "maçã")
frase_teste = frase_teste.replace("Banana", "Maçã")
print(frase_teste)