# -*- coding: utf-8 -*-
"""L5 E5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1moQT15ck-uHx_xPHrBKRRoEFduZ5XYRt
"""

#Escreva um programa que seleciona o nome de um arquivo do caminho informado. 
#O programa deve possuir um caminho completo para um arquivo e deve 
#imprimir somente o nome do arquivo, sem extensão.

#Para a string: C:/meus vídeos/viagens/salvador/virada_do_ano.mp4
#O programa deve exibir: virada_do_ano

#Main
caminho = "C:/meus vídeos/viagens/salvador/virada_do_ano.mp4"

caminho = caminho[caminho.rfind("/")+1:caminho.rfind(".")]
print(caminho)