# -*- coding: utf-8 -*-
"""L5 E4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y5xj5RMqS6ZK49sY9wmrAbRREsNHHjdu
"""

#Escreva um programa para a verificação da formatação válida de CPFs. 
#O programa deve receber uma string no formato xxx.xxx.xxx-xx. 
#O programa então deve verificar se a string inserida é constituída 
#por números e os separadores válidos.

#Exemplo de entrada: 111.222.333-44
#Saída do programa: Formato de CPF Válido.
#Exemplo de entrada: 111.2a2.3b3-44
#Saída do programa: O CPF informado não tem um formato válido.

#Main
TAM_CPF = 14
cpf = input("Por favor insira o cpf: ")
flag = True

if(len(cpf) != TAM_CPF):
  flag = False
elif((cpf[3] != ".") or (cpf[7] != ".") or (cpf[-3] != "-")):
  flag = False
else:
  for i in range(TAM_CPF):
    if((i != 3) and (i != 7) and (i != 11)):
      c = cpf[i]
      if(not c.isdigit()):
        flag = False

if(flag):
  print("Formato de CPF Válido.")
else:
  print("O CPF informado não tem um formato válido.")