# -*- coding: utf-8 -*-
"""L5 E3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z69N7syQ-ngJnJA-FvYMq9VxU61ae3rT
"""

#Escreva um programa que permita ao usuário digitar o seu nome. 
#Em seguida o programa deve exibir o nome do usuário de trás para frente,
#uma letra por linha, utilizando somente letras maiúsculas.

#Exemplo de entrada: Felipe
#O programa exibirá:
#E
#P
#I
#L
#E
#F

#Main
nome = input("Por favor insira o nome: ")

for i in range(len(nome)):
  c = nome[len(nome) - 1 - i]
  print(c.upper())