# -*- coding: utf-8 -*-
"""L5 E1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oz0Tp0RX7eFf9ILXjRKtrbonRMRsgs0M
"""

#Escreva um programa que receba os nomes e as notas de cinco
#alunos e exiba na tela o aluno com maior nota e a média da turma.

#Biblioteca
import numpy as np

#Main
notas = []
nomes = []
for i in range(5):
  n = input("Por favor insira o nome do aluno %d: " % (i+1))
  nomes.append(n)
  j = float(input("Por favor insira a nota do aluno %d: " % (i+1)))
  notas.append(j)

#aluno com maior nota
nosso_max = max(notas)
for i in range(5):
  if(notas[i] == nosso_max):
    print("O aluno com maior nota é o %s" % nomes[i])

#média da turma
print("A média da turma é %.2f" % np.average(notas))